version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "llsbet-digital"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "llsbet-digital"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "llsbet-digital"
    commit-message:
      prefix: "ci(deps):"
      include: "scope"
